### Coding Backpropagation From Scratch: On Multiple Neurons

In [1]:
import numpy as np

In [3]:
# Initial inputs
inputs = np.array([1, 2, 3, 4])

# Initial weights and biases
weights = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
])

biases = np.array([0.1, 0.2, 0.3])

# Learning rate
learning_rate = 0.001

# ReLU activation function and its derivative
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

# Training loop
for iteration in range(200):
    # Forward pass
    z = np.dot(weights, inputs) + biases
    a = relu(z)
    y = np.sum(a)
    
    # Calculate loss
    loss = y ** 2
    
    # Backward pass
    # Gradient of loss with respect to output y
    dL_dy = 2 * y
    
    # Gradient of y with respect to a
    dy_da = np.ones_like(a)
    
    # Gradient of loss with respect to a
    dL_da =  dL_dy * dy_da
    
    # Gradient of a with respect to z (ReLU derivative)
    da_dz = relu_derivative(z)
    
    # Gradient of loss with respect to z
    dL_dz = dL_da * da_dz
    dL_db = dL_dz
    
    # Gradient of z with respect to weights and biases
    dL_dW =  np.outer(dL_dz, inputs)
    
    # Update weights and biases
    weights -= learning_rate * dL_dW
    biases -= learning_rate * dL_db
    
    # Print the loss every 20 iterations
    if iteration % 20 == 0:
        print(f'Iteraton {iteration}, Loss: {loss}')
        

# Final weights and biases
print("Final weights:\n", weights)
print("Final biases:\n", biases)

Iteraton 0, Loss: 466.56000000000006
Iteraton 20, Loss: 5.32959636083938
Iteraton 40, Loss: 0.41191523404899866
Iteraton 60, Loss: 0.031836212079467595
Iteraton 80, Loss: 0.002460565465389601
Iteraton 100, Loss: 0.000190172825660145
Iteraton 120, Loss: 1.4698126966451542e-05
Iteraton 140, Loss: 1.1359926717815175e-06
Iteraton 160, Loss: 8.779889800154524e-08
Iteraton 180, Loss: 6.7858241357822796e-09
Final weights:
 [[-0.00698895 -0.01397789 -0.02096684 -0.02795579]
 [ 0.25975286  0.11950572 -0.02074143 -0.16098857]
 [ 0.53548461  0.27096922  0.00645383 -0.25806156]]
Final biases:
 [-0.00698895 -0.04024714 -0.06451539]
